#!/bin/bash
architecture="i386"

nasm -f bin $architecture/boot.asm -o binaries/boot-$architecture.bin
echo Compiled bootloader
nasm common/kernel_entry.asm -f elf -o binaries/ke-$architecture.o
i386-elf-gcc -ffreestanding -m32 -g -c $architecture/kernel.c -o binaries/kernel-$architecture.o
echo Compiled kernel

i386-elf-ld -o binaries/fk-$architecture.bin -Ttext 0x1000 binaries/ke-$architecture.o binaries/kernel-$architecture.o --oformat binary
echo Linked files

cat binaries/boot-$architecture.bin binaries/fk-$architecture.bin > binaries/kkOS-$architecture.bin
echo Concatenated, running...

# Run the OS in QEMU
qemu-system-x86_64 -drive format=raw,file="binaries/kkOS-i386.bin",index=0,if=floppy,  -m 128M -d cpu_reset -D logs.txt
